/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates.$certificateId'
import { Route as CertificatesNewRouteImport } from './routes/certificates.new'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as OrganisationsIndexRouteImport } from './routes/organisations.index'
import { Route as OrganisationsOrgIdRouteImport } from './routes/organisations.$orgId'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as TrackingIndexRouteImport } from './routes/tracking.index'
import { Route as SettingsAutomationsIndexRouteImport } from './routes/settings.automations.index'
import { Route as SettingsAutomationsAutomationIdRouteImport } from './routes/settings.automations.$automationId'
import { Route as SettingsStudioIndexRouteImport } from './routes/settings.studio.index'
import { Route as SettingsStudioCertificatesIndexRouteImport } from './routes/settings.studio.certificates.index'
import { Route as SettingsStudioCertificatesCertificateIdRouteImport } from './routes/settings.studio.certificates.$certificateId'
import { Route as SettingsStudioCoursesCourseIdRouteImport } from './routes/settings.studio.courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificatesNewRoute = CertificatesNewRouteImport.update({
  id: '/certificates/new',
  path: '/certificates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsIndexRoute = OrganisationsIndexRouteImport.update({
  id: '/organisations/',
  path: '/organisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsOrgIdRoute = OrganisationsOrgIdRouteImport.update({
  id: '/organisations/$orgId',
  path: '/organisations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAutomationsIndexRoute =
  SettingsAutomationsIndexRouteImport.update({
    id: '/settings/automations/',
    path: '/settings/automations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAutomationsAutomationIdRoute =
  SettingsAutomationsAutomationIdRouteImport.update({
    id: '/settings/automations/$automationId',
    path: '/settings/automations/$automationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsStudioIndexRoute = SettingsStudioIndexRouteImport.update({
  id: '/settings/studio/',
  path: '/settings/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStudioCertificatesIndexRoute =
  SettingsStudioCertificatesIndexRouteImport.update({
    id: '/settings/studio/certificates/',
    path: '/settings/studio/certificates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsStudioCertificatesCertificateIdRoute =
  SettingsStudioCertificatesCertificateIdRouteImport.update({
    id: '/settings/studio/certificates/$certificateId',
    path: '/settings/studio/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsStudioCoursesCourseIdRoute =
  SettingsStudioCoursesCourseIdRouteImport.update({
    id: '/settings/studio/courses/$courseId',
    path: '/settings/studio/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/new': typeof CertificatesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/organisations/$orgId': typeof OrganisationsOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/settings/automations/$automationId': typeof SettingsAutomationsAutomationIdRoute
  '/settings/automations/': typeof SettingsAutomationsIndexRoute
  '/settings/studio/': typeof SettingsStudioIndexRoute
  '/settings/studio/certificates/$certificateId': typeof SettingsStudioCertificatesCertificateIdRoute
  '/settings/studio/courses/$courseId': typeof SettingsStudioCoursesCourseIdRoute
  '/settings/studio/certificates/': typeof SettingsStudioCertificatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/new': typeof CertificatesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/organisations/$orgId': typeof OrganisationsOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/certificates': typeof CertificatesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/organisations': typeof OrganisationsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/settings/automations/$automationId': typeof SettingsAutomationsAutomationIdRoute
  '/settings/automations': typeof SettingsAutomationsIndexRoute
  '/settings/studio': typeof SettingsStudioIndexRoute
  '/settings/studio/certificates/$certificateId': typeof SettingsStudioCertificatesCertificateIdRoute
  '/settings/studio/courses/$courseId': typeof SettingsStudioCoursesCourseIdRoute
  '/settings/studio/certificates': typeof SettingsStudioCertificatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/certificates/new': typeof CertificatesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/organisations/$orgId': typeof OrganisationsOrgIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/settings/automations/$automationId': typeof SettingsAutomationsAutomationIdRoute
  '/settings/automations/': typeof SettingsAutomationsIndexRoute
  '/settings/studio/': typeof SettingsStudioIndexRoute
  '/settings/studio/certificates/$certificateId': typeof SettingsStudioCertificatesCertificateIdRoute
  '/settings/studio/courses/$courseId': typeof SettingsStudioCoursesCourseIdRoute
  '/settings/studio/certificates/': typeof SettingsStudioCertificatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certificates/$certificateId'
    | '/certificates/new'
    | '/courses/$courseId'
    | '/organisations/$orgId'
    | '/people/$personId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/team'
    | '/certificates/'
    | '/courses/'
    | '/organisations/'
    | '/people/'
    | '/sessions/'
    | '/settings/'
    | '/tracking/'
    | '/settings/automations/$automationId'
    | '/settings/automations/'
    | '/settings/studio/'
    | '/settings/studio/certificates/$certificateId'
    | '/settings/studio/courses/$courseId'
    | '/settings/studio/certificates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certificates/$certificateId'
    | '/certificates/new'
    | '/courses/$courseId'
    | '/organisations/$orgId'
    | '/people/$personId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/team'
    | '/certificates'
    | '/courses'
    | '/organisations'
    | '/people'
    | '/sessions'
    | '/settings'
    | '/tracking'
    | '/settings/automations/$automationId'
    | '/settings/automations'
    | '/settings/studio'
    | '/settings/studio/certificates/$certificateId'
    | '/settings/studio/courses/$courseId'
    | '/settings/studio/certificates'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/certificates/$certificateId'
    | '/certificates/new'
    | '/courses/$courseId'
    | '/organisations/$orgId'
    | '/people/$personId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/team'
    | '/certificates/'
    | '/courses/'
    | '/organisations/'
    | '/people/'
    | '/sessions/'
    | '/settings/'
    | '/tracking/'
    | '/settings/automations/$automationId'
    | '/settings/automations/'
    | '/settings/studio/'
    | '/settings/studio/certificates/$certificateId'
    | '/settings/studio/courses/$courseId'
    | '/settings/studio/certificates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CertificatesNewRoute: typeof CertificatesNewRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  OrganisationsOrgIdRoute: typeof OrganisationsOrgIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  OrganisationsIndexRoute: typeof OrganisationsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
  SettingsAutomationsAutomationIdRoute: typeof SettingsAutomationsAutomationIdRoute
  SettingsAutomationsIndexRoute: typeof SettingsAutomationsIndexRoute
  SettingsStudioIndexRoute: typeof SettingsStudioIndexRoute
  SettingsStudioCertificatesCertificateIdRoute: typeof SettingsStudioCertificatesCertificateIdRoute
  SettingsStudioCoursesCourseIdRoute: typeof SettingsStudioCoursesCourseIdRoute
  SettingsStudioCertificatesIndexRoute: typeof SettingsStudioCertificatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/new': {
      id: '/certificates/new'
      path: '/certificates/new'
      fullPath: '/certificates/new'
      preLoaderRoute: typeof CertificatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/': {
      id: '/organisations/'
      path: '/organisations'
      fullPath: '/organisations/'
      preLoaderRoute: typeof OrganisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/$orgId': {
      id: '/organisations/$orgId'
      path: '/organisations/$orgId'
      fullPath: '/organisations/$orgId'
      preLoaderRoute: typeof OrganisationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/automations/': {
      id: '/settings/automations/'
      path: '/settings/automations'
      fullPath: '/settings/automations/'
      preLoaderRoute: typeof SettingsAutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/automations/$automationId': {
      id: '/settings/automations/$automationId'
      path: '/settings/automations/$automationId'
      fullPath: '/settings/automations/$automationId'
      preLoaderRoute: typeof SettingsAutomationsAutomationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/studio/': {
      id: '/settings/studio/'
      path: '/settings/studio'
      fullPath: '/settings/studio/'
      preLoaderRoute: typeof SettingsStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/studio/certificates/': {
      id: '/settings/studio/certificates/'
      path: '/settings/studio/certificates'
      fullPath: '/settings/studio/certificates/'
      preLoaderRoute: typeof SettingsStudioCertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/studio/certificates/$certificateId': {
      id: '/settings/studio/certificates/$certificateId'
      path: '/settings/studio/certificates/$certificateId'
      fullPath: '/settings/studio/certificates/$certificateId'
      preLoaderRoute: typeof SettingsStudioCertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/studio/courses/$courseId': {
      id: '/settings/studio/courses/$courseId'
      path: '/settings/studio/courses/$courseId'
      fullPath: '/settings/studio/courses/$courseId'
      preLoaderRoute: typeof SettingsStudioCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CertificatesNewRoute: CertificatesNewRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  OrganisationsOrgIdRoute: OrganisationsOrgIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  OrganisationsIndexRoute: OrganisationsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TrackingIndexRoute: TrackingIndexRoute,
  SettingsAutomationsAutomationIdRoute: SettingsAutomationsAutomationIdRoute,
  SettingsAutomationsIndexRoute: SettingsAutomationsIndexRoute,
  SettingsStudioIndexRoute: SettingsStudioIndexRoute,
  SettingsStudioCertificatesCertificateIdRoute:
    SettingsStudioCertificatesCertificateIdRoute,
  SettingsStudioCoursesCourseIdRoute: SettingsStudioCoursesCourseIdRoute,
  SettingsStudioCertificatesIndexRoute: SettingsStudioCertificatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
